:batch-asciidoc: ./
:toc: left
:toclevels: 4

[[whatsNew]]

== Spring Batch 4.2 新特性

Spring Batch 4.2 添加了下面的新特性：

* 使用 https://micrometer.io[Micrometer] 来支持批量指标（batch metrics）
* 支持从 https://kafka.apache.org[Apache Kafka] topics 读取/写入（reading/writing） 数据
* 支持从 https://avro.apache.org[Apache Avro] 资源中读取/写入（reading/writing） 数据
* 改进支持文档

[[whatsNewMetrics]]
=== 使用 Micrometer 的批量指标

本发行版本介绍了可以让你通过使用 Micrometer 来监控你的批量作业。在默认的情况下，Spring Batch 将会收集相关批量指标
（包括，作业时间，步骤的时间，读取和写入的项目，以及其他的相关信息），和将这些指标通过 `spring.batch` 前缀（prefix）注册到 Micrometer 的全局指标中。

这些指标可以发布到任何能够支持 Micrometer 的  https://micrometer.io/docs/concepts#_supported_monitoring_systems[监控系统（monitoring system）]中。


有关这个新特性的更多细节，请参考
<<monitoring-and-metrics.adoc#monitoring-and-metrics,Monitoring and metrics>> 章节中的内容。

[[whatsNewKafka]]
=== Apache Kafka item reader/writer

This release adds a new `KafkaItemReader` and `KafkaItemWriter` to read data from and
write it to Kafka topics. For more details about these new components, please refer
to the https://docs.spring.io/spring-batch/4.2.x/api/index.html[Javadoc].

[[whatsNewAvro]]
=== Apache Avro item reader/writer

This release adds a new `AvroItemReader` and `AvroItemWriter` to read data from and
write it to Avro resources. For more details about these new components, please refer
to the https://docs.spring.io/spring-batch/4.2.x/api/index.html[Javadoc].

[[whatsNewDocs]]
=== Documentation updates

The reference documentation has been updated to match the same style as other
Spring projects.
